"""empty message

Revision ID: 1730b97c93fa
Revises: e89dfd48d38b
Create Date: 2023-05-01 16:35:04.608055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1730b97c93fa'
down_revision = 'e89dfd48d38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvoted_requests', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('upvoted_requests')

    # ### end Alembic commands ###
