"""empty message

Revision ID: 7dd2f5f465dc
Revises: e35e78c0afbd
Create Date: 2023-04-28 09:23:08.217490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dd2f5f465dc'
down_revision = 'e35e78c0afbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
