"""empty message

Revision ID: d35479947422
Revises: 1730b97c93fa
Create Date: 2023-05-02 13:21:59.497576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd35479947422'
down_revision = '1730b97c93fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_request',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(length=2500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['id'])

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('requester',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_constraint('request_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('request_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['requester'], ['id'])
        batch_op.drop_column('message_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('upvoted_requests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvoted_requests', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('request_ibfk_1', 'message', ['message_id'], ['id'])
        batch_op.create_foreign_key('request_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.alter_column('requester',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=2500),
               existing_nullable=False)
        batch_op.drop_column('request_id')

    op.drop_table('user_request')
    # ### end Alembic commands ###
